<a href="https://colab.research.google.com/github/deep-dive-coding-data-science/Prework/blob/master/Logistic_Regression_Exercise_with_Solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

from sklearn import metrics 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score

In [2]:
df = pd.read_csv("/content/drive/My Drive/Deep Dive Data Science - Cohort 1/Data/Data Pass Fail.csv")
df.head()

Self_Study_Daily  Tution_Monthly  Pass_Or_Fail
0                 7              27             1
1                 2              43             0
2                 7              26             1
3                 8              29             1
4                 3              42             0

In [0]:
x = df.drop("Pass_Or_Fail",axis = 1)
y = df.Pass_Or_Fail

In [0]:
x_train, x_test, y_train, y_test = train_test_split(x, y)

In [0]:
logistic_regression = LogisticRegression()

In [6]:
logistic_regression.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
y_pred = logistic_regression.predict(x_test)

In [8]:
accuracy = metrics.accuracy_score(y_test, y_pred)
accuracy_percentage = 100 * accuracy
accuracy_percentage

97.6

In [9]:
First_Friend = logistic_regression.predict((np.array([8, 38]).reshape(1, -1)))
First_Friend

array([0])

In [10]:
confusion_matrix(y_test,y_pred)

array([[122,   5],
       [  1, 122]])

In [15]:
y_pred=logistic_regression.predict(((np.array([7,27])).reshape(1,-1)))
y_pred

array([1])